# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17IFBtjryyH2ZRNWr8l9b-CiicFqnHmzd

Dataset Exploration
"""

import pandas as pd
import numpy as np
import re

# ============================================================
# FILE NAMES
# ============================================================

tsf_file = "australian_electricity_demand_dataset.tsf"
csv_file = "electricityconsumptionbenchmarkssurveydataaergovhack.csv"


# ============================================================
# DATASET 1: AUSTRALIAN ELECTRICITY DEMAND (.tsf)
# ============================================================

def load_tsf_dataset(filename):

    records = []

    with open(filename, "r") as file:
        in_data = False

        for line in file:
            line = line.strip()

            # Skip empty lines
            if not line:
                continue

            # Start reading data after @data
            if line.lower() == "@data":
                in_data = True
                continue

            # Ignore metadata before @data
            if not in_data:
                continue

            # Each line has:
            # series_name:state:start_timestamp:values
            parts = line.split(":", 3)

            if len(parts) != 4:
                continue

            series_name = parts[0]
            state = parts[1]
            start_timestamp = parts[2]
            values_string = parts[3]

            # Convert comma-separated demand values into numbers
            values = values_string.split(",")

            for index, value in enumerate(values):

                try:
                    demand = float(value)
                except ValueError:
                    continue

                records.append({
                    "series_name": series_name,
                    "state": state,
                    "start_timestamp": start_timestamp,
                    "interval": index,
                    "demand": demand
                })

    return pd.DataFrame(records)


df1 = load_tsf_dataset(tsf_file)


# ============================================================
# DATASET 2: ELECTRICITY CONSUMPTION BENCHMARKS (.csv)
# ============================================================

df2 = pd.read_csv(csv_file)


# ============================================================
# BASIC EXPLORATION
# ============================================================

print("=" * 70)
print("DATASET 1: AUSTRALIAN ELECTRICITY DEMAND")
print("=" * 70)

print("\nShape:")
print(df1.shape)

print("\nColumns:")
print(df1.columns.tolist())

print("\nData types:")
print(df1.dtypes)

print("\nStates:")
print(df1["state"].value_counts())

print("\nMissing values:")
print(df1.isnull().sum())

print("\nFirst 5 rows:")
print(df1.head())

print("\nDemand statistics:")
print(df1["demand"].describe())


print("\n\n")
print("=" * 70)
print("DATASET 2: ELECTRICITY CONSUMPTION BENCHMARKS")
print("=" * 70)

print("\nShape:")
print(df2.shape)

print("\nColumns:")
print(df2.columns.tolist())

print("\nData types:")
print(df2.dtypes)

print("\nMissing values:")
print(df2.isnull().sum())

print("\nFirst 5 rows:")
print(df2.head())

print("\nRespondents:")
print(df2["respondent"].nunique())

print("\nTypes:")
print(df2["TYPE"].value_counts())

print("\nDates:")
print(df2["OUTPUT_DATE"].min(), "to", df2["OUTPUT_DATE"].max())


# ============================================================
# HALF-HOURLY COLUMNS IN DATASET 2
# ============================================================

half_hour_columns = [
    column for column in df2.columns
    if column.startswith("E_")
]

print("\nNumber of half-hourly consumption columns:")
print(len(half_hour_columns))

print("\nHalf-hourly columns:")
print(half_hour_columns)

print("\nTotal missing values in half-hourly data:")
print(df2[half_hour_columns].isnull().sum().sum())

"""Dataset Prepare for Machine learning

"""

# ============================================================
# PREPARE DATASET 1
# ============================================================

# Convert starting timestamp to datetime
df1["start_timestamp"] = pd.to_datetime(
    df1["start_timestamp"],
    format="%Y-%m-%d %H-%M-%S"
)

# Create the actual timestamp for each half-hour observation
df1["timestamp"] = (
    df1["start_timestamp"]
    + pd.to_timedelta(df1["interval"] * 30, unit="minutes")
)

# Sort the data correctly
df1 = df1.sort_values(
    ["state", "timestamp"]
).reset_index(drop=True)

# Create previous-demand features
df1["lag_1"] = (
    df1.groupby("state")["demand"]
    .shift(1)
)

df1["lag_2"] = (
    df1.groupby("state")["demand"]
    .shift(2)
)

df1["lag_48"] = (
    df1.groupby("state")["demand"]
    .shift(48)
)

df1["lag_336"] = (
    df1.groupby("state")["demand"]
    .shift(336)
)

# Time-based features
df1["hour"] = df1["timestamp"].dt.hour
df1["day_of_week"] = df1["timestamp"].dt.dayofweek
df1["month"] = df1["timestamp"].dt.month

# Remove rows where lag values cannot be calculated
df1 = df1.dropna().reset_index(drop=True)

# Check the result
print("Dataset 1 shape after preparation:")
print(df1.shape)

print("\nFirst 5 rows:")
print(
    df1[
        [
            "state",
            "timestamp",
            "demand",
            "lag_1",
            "lag_2",
            "lag_48",
            "lag_336",
            "hour",
            "day_of_week",
            "month"
        ]
    ].head()
)

# ============================================================
# PREPARE DATASET 2
# ============================================================

# Convert date column to datetime
df2["OUTPUT_DATE"] = pd.to_datetime(
    df2["OUTPUT_DATE"],
    dayfirst=True
)

# Get the 48 half-hourly electricity columns
half_hour_columns = [
    column for column in df2.columns
    if column.startswith("E_")
]

print("Number of half-hourly columns:", len(half_hour_columns))


# ============================================================
# RESHAPE FROM WIDE TO LONG FORMAT
# ============================================================

df2_long = df2.melt(
    id_vars=[
        "respondent",
        "OUTPUT_DATE",
        "TYPE"
    ],
    value_vars=half_hour_columns,
    var_name="time",
    value_name="consumption_wh"
)

# Sort observations chronologically for each household/type
df2_long = df2_long.sort_values(
    ["respondent", "TYPE", "OUTPUT_DATE", "time"]
).reset_index(drop=True)


# ============================================================
# EXTRACT TIME INFORMATION
# ============================================================

# Convert E_0000_WH -> 00:00
# Convert E_0030_WH -> 00:30 etc.

df2_long["time_clean"] = (
    df2_long["time"]
    .str.replace("E_", "", regex=False)
    .str.replace("_WH", "", regex=False)
)

df2_long["hour"] = (
    df2_long["time_clean"]
    .str[:2]
    .astype(int)
)

df2_long["minute"] = (
    df2_long["time_clean"]
    .str[2:]
    .astype(int)
)


# ============================================================
# CREATE DATETIME
# ============================================================

df2_long["timestamp"] = (
    df2_long["OUTPUT_DATE"]
    + pd.to_timedelta(df2_long["hour"], unit="hours")
    + pd.to_timedelta(df2_long["minute"], unit="minutes")
)


# ============================================================
# CREATE PREVIOUS-CONSUMPTION FEATURES
# ============================================================

# Previous half-hour
df2_long["lag_1"] = (
    df2_long
    .groupby(["respondent", "TYPE"])["consumption_wh"]
    .shift(1)
)

# Previous hour
df2_long["lag_2"] = (
    df2_long
    .groupby(["respondent", "TYPE"])["consumption_wh"]
    .shift(2)
)

# Previous day
df2_long["lag_48"] = (
    df2_long
    .groupby(["respondent", "TYPE"])["consumption_wh"]
    .shift(48)
)


# ============================================================
# ADD DAY INFORMATION
# ============================================================

df2_long["day_of_week"] = (
    df2_long["timestamp"].dt.dayofweek
)

df2_long["month"] = (
    df2_long["timestamp"].dt.month
)


# ============================================================
# REMOVE ROWS WITHOUT LAG VALUES
# ============================================================

df2_long = df2_long.dropna().reset_index(drop=True)


# ============================================================
# CHECK RESULT
# ============================================================

print("\nDataset 2 shape after preparation:")
print(df2_long.shape)

print("\nColumns:")
print(df2_long.columns.tolist())

print("\nFirst 10 rows:")
print(
    df2_long[
        [
            "respondent",
            "TYPE",
            "timestamp",
            "consumption_wh",
            "lag_1",
            "lag_2",
            "lag_48",
            "day_of_week",
            "month"
        ]
    ].head(10)
)

# ============================================================
# STEP 4 — DEFINE FEATURES AND TARGET
# ============================================================

# ------------------------------------------------------------
# DATASET 1: Australian Electricity Demand
# ------------------------------------------------------------

features_1 = [
    "lag_1",
    "lag_2",
    "lag_48",
    "lag_336",
    "hour",
    "day_of_week",
    "month"
]

X1 = df1[features_1]
y1 = df1["demand"]

print("=" * 60)
print("DATASET 1")
print("=" * 60)

print("Features:")
print(X1.columns.tolist())

print("\nX1 shape:", X1.shape)
print("y1 shape:", y1.shape)

print("\nTarget statistics:")
print(y1.describe())


# ------------------------------------------------------------
# DATASET 2: Household Electricity Consumption
# ------------------------------------------------------------

features_2 = [
    "lag_1",
    "lag_2",
    "lag_48",
    "hour",
    "minute",
    "day_of_week",
    "month"
]

X2 = df2_long[features_2]
y2 = df2_long["consumption_wh"]

print("\n")
print("=" * 60)
print("DATASET 2")
print("=" * 60)

print("Features:")
print(X2.columns.tolist())

print("\nX2 shape:", X2.shape)
print("y2 shape:", y2.shape)

print("\nTarget statistics:")
print(y2.describe())

# ============================================================
# STEP 5 — TRAIN / TEST SPLIT
# ============================================================

# ------------------------------------------------------------
# DATASET 1
# ------------------------------------------------------------

split_1 = int(len(X1) * 0.8)

X1_train = X1.iloc[:split_1]
X1_test = X1.iloc[split_1:]

y1_train = y1.iloc[:split_1]
y1_test = y1.iloc[split_1:]


print("=" * 60)
print("DATASET 1 — TRAIN / TEST")
print("=" * 60)

print("Training samples:", len(X1_train))
print("Testing samples:", len(X1_test))

print(
    "Training target range:",
    y1_train.index.min(),
    "to",
    y1_train.index.max()
)

print(
    "Testing target range:",
    y1_test.index.min(),
    "to",
    y1_test.index.max()
)


# ------------------------------------------------------------
# DATASET 2
# ------------------------------------------------------------

split_2 = int(len(X2) * 0.8)

X2_train = X2.iloc[:split_2]
X2_test = X2.iloc[split_2:]

y2_train = y2.iloc[:split_2]
y2_test = y2.iloc[split_2:]


print("\n")
print("=" * 60)
print("DATASET 2 — TRAIN / TEST")
print("=" * 60)

print("Training samples:", len(X2_train))
print("Testing samples:", len(X2_test))

print(
    "Training target range:",
    y2_train.index.min(),
    "to",
    y2_train.index.max()
)

print(
    "Testing target range:",
    y2_test.index.min(),
    "to",
    y2_test.index.max()
)

# ============================================================
# STEP 6 — DECISION TREE REGRESSION
# ============================================================

from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np


# ------------------------------------------------------------
# DATASET 1 — DECISION TREE
# ------------------------------------------------------------

dt_1 = DecisionTreeRegressor(
    max_depth=10,
    random_state=42
)

dt_1.fit(X1_train, y1_train)

y1_pred_dt = dt_1.predict(X1_test)


# Evaluate Dataset 1
mae_1_dt = mean_absolute_error(y1_test, y1_pred_dt)

rmse_1_dt = np.sqrt(
    mean_squared_error(y1_test, y1_pred_dt)
)


print("=" * 60)
print("DATASET 1 — DECISION TREE")
print("=" * 60)

print("MAE:", mae_1_dt)
print("RMSE:", rmse_1_dt)


# ------------------------------------------------------------
# DATASET 2 — DECISION TREE
# ------------------------------------------------------------

dt_2 = DecisionTreeRegressor(
    max_depth=10,
    random_state=42
)

dt_2.fit(X2_train, y2_train)

y2_pred_dt = dt_2.predict(X2_test)


# Evaluate Dataset 2
mae_2_dt = mean_absolute_error(y2_test, y2_pred_dt)

rmse_2_dt = np.sqrt(
    mean_squared_error(y2_test, y2_pred_dt)
)


print("\n")
print("=" * 60)
print("DATASET 2 — DECISION TREE")
print("=" * 60)

print("MAE:", mae_2_dt)
print("RMSE:", rmse_2_dt)

# ============================================================
# STEP 7 — kNN REGRESSION
# ============================================================

from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np


# ============================================================
# DATASET 1 — kNN
# ============================================================

scaler_1 = StandardScaler()

X1_train_scaled = scaler_1.fit_transform(X1_train)
X1_test_scaled = scaler_1.transform(X1_test)


knn_1 = KNeighborsRegressor(
    n_neighbors=5
)

knn_1.fit(
    X1_train_scaled,
    y1_train
)

y1_pred_knn = knn_1.predict(X1_test_scaled)


# Evaluate Dataset 1

mae_1_knn = mean_absolute_error(
    y1_test,
    y1_pred_knn
)

rmse_1_knn = np.sqrt(
    mean_squared_error(
        y1_test,
        y1_pred_knn
    )
)


print("=" * 60)
print("DATASET 1 — kNN")
print("=" * 60)

print("MAE:", mae_1_knn)
print("RMSE:", rmse_1_knn)


# ============================================================
# DATASET 2 — kNN
# ============================================================

scaler_2 = StandardScaler()

X2_train_scaled = scaler_2.fit_transform(X2_train)
X2_test_scaled = scaler_2.transform(X2_test)


knn_2 = KNeighborsRegressor(
    n_neighbors=5
)

knn_2.fit(
    X2_train_scaled,
    y2_train
)

y2_pred_knn = knn_2.predict(X2_test_scaled)


# Evaluate Dataset 2

mae_2_knn = mean_absolute_error(
    y2_test,
    y2_pred_knn
)

rmse_2_knn = np.sqrt(
    mean_squared_error(
        y2_test,
        y2_pred_knn
    )
)


print("\n")
print("=" * 60)
print("DATASET 2 — kNN")
print("=" * 60)

print("MAE:", mae_2_knn)
print("RMSE:", rmse_2_knn)

# ============================================================
# STEP 8 — MODEL COMPARISON
# ============================================================

results = pd.DataFrame({
    "Dataset": [
        "Australian Electricity Demand",
        "Australian Electricity Demand",
        "Household Electricity Consumption",
        "Household Electricity Consumption"
    ],
    "Model": [
        "Decision Tree",
        "kNN",
        "Decision Tree",
        "kNN"
    ],
    "MAE": [
        mae_1_dt,
        mae_1_knn,
        mae_2_dt,
        mae_2_knn
    ],
    "RMSE": [
        rmse_1_dt,
        rmse_1_knn,
        rmse_2_dt,
        rmse_2_knn
    ]
})

print(results)

# ============================================================
# STEP 9 — DECISION TREE FEATURE IMPORTANCE
# ============================================================

feature_importance_1 = pd.DataFrame({
    "Feature": X1.columns,
    "Importance": dt_1.feature_importances_
}).sort_values(
    "Importance",
    ascending=False
)

print("=" * 60)
print("DATASET 1 — DECISION TREE FEATURE IMPORTANCE")
print("=" * 60)

print(feature_importance_1)


feature_importance_2 = pd.DataFrame({
    "Feature": X2.columns,
    "Importance": dt_2.feature_importances_
}).sort_values(
    "Importance",
    ascending=False
)

print("\n")
print("=" * 60)
print("DATASET 2 — DECISION TREE FEATURE IMPORTANCE")
print("=" * 60)

print(feature_importance_2)

# ============================================================
# STEP 10 — VISUALISATIONS
# ============================================================

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


# ============================================================
# 1. DATASET 1 — ACTUAL VS PREDICTED
# ============================================================

sample_size = 500

# Use the same random test observations for both models
rng = np.random.default_rng(42)
sample_indices_1 = rng.choice(
    len(y1_test),
    size=sample_size,
    replace=False
)

actual_1 = np.array(y1_test)[sample_indices_1]
pred_dt_1 = y1_pred_dt[sample_indices_1]
pred_knn_1 = y1_pred_knn[sample_indices_1]

plt.figure(figsize=(12, 6))

plt.plot(
    actual_1,
    label="Actual Demand",
    linewidth=1.5
)

plt.plot(
    pred_dt_1,
    label="Decision Tree",
    linewidth=1
)

plt.plot(
    pred_knn_1,
    label="kNN",
    linewidth=1
)

plt.title("Dataset 1 — Actual vs Predicted Electricity Demand")
plt.xlabel("Test Observation")
plt.ylabel("Electricity Demand")
plt.legend()
plt.tight_layout()
plt.show()


# ============================================================
# 2. DATASET 2 — ACTUAL VS PREDICTED
# ============================================================

sample_indices_2 = rng.choice(
    len(y2_test),
    size=sample_size,
    replace=False
)

actual_2 = np.array(y2_test)[sample_indices_2]
pred_dt_2 = y2_pred_dt[sample_indices_2]
pred_knn_2 = y2_pred_knn[sample_indices_2]

plt.figure(figsize=(12, 6))

plt.plot(
    actual_2,
    label="Actual Consumption",
    linewidth=1.5
)

plt.plot(
    pred_dt_2,
    label="Decision Tree",
    linewidth=1
)

plt.plot(
    pred_knn_2,
    label="kNN",
    linewidth=1
)

plt.title("Dataset 2 — Actual vs Predicted Household Consumption")
plt.xlabel("Test Observation")
plt.ylabel("Electricity Consumption (Wh)")
plt.legend()
plt.tight_layout()
plt.show()


# ============================================================
# 3. MODEL PERFORMANCE COMPARISON
# ============================================================

results = pd.DataFrame({
    "Dataset": [
        "Dataset 1",
        "Dataset 1",
        "Dataset 2",
        "Dataset 2"
    ],
    "Model": [
        "Decision Tree",
        "kNN",
        "Decision Tree",
        "kNN"
    ],
    "MAE": [
        mae_1_dt,
        mae_1_knn,
        mae_2_dt,
        mae_2_knn
    ],
    "RMSE": [
        rmse_1_dt,
        rmse_1_knn,
        rmse_2_dt,
        rmse_2_knn
    ]
})

x = np.arange(len(results))
width = 0.35

plt.figure(figsize=(10, 6))

plt.bar(
    x - width / 2,
    results["MAE"],
    width,
    label="MAE"
)

plt.bar(
    x + width / 2,
    results["RMSE"],
    width,
    label="RMSE"
)

plt.xticks(
    x,
    [
        "D1 Decision Tree",
        "D1 kNN",
        "D2 Decision Tree",
        "D2 kNN"
    ]
)

plt.ylabel("Error")
plt.title("Model Performance Comparison")
plt.legend()
plt.tight_layout()
plt.show()


# ============================================================
# 4. FEATURE IMPORTANCE — DATASET 1
# ============================================================

plt.figure(figsize=(10, 6))

plt.barh(
    feature_importance_1["Feature"],
    feature_importance_1["Importance"]
)

plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Decision Tree Feature Importance — Dataset 1")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()


# ============================================================
# 5. FEATURE IMPORTANCE — DATASET 2
# ============================================================

plt.figure(figsize=(10, 6))

plt.barh(
    feature_importance_2["Feature"],
    feature_importance_2["Importance"]
)

plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Decision Tree Feature Importance — Dataset 2")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()